/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() throws Exception {
        App classUnderTest = new App();
        System.out.println("Print from test!");
        assertNotNull("app should have a greetinggggggg", classUnderTest.getGreeting());
    }
}
