package com.github.fontys;


import com.github.fontys.trackingsystem.TrackingManager;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
       new TrackingManager();
    }
}
